#
# plot dive profiles
#

# arguments
# - CSV file with time [min] and pressure [bar]
# - tank size


library(Hmisc)
library(grid)

if (length(args) != 6) {
    stop('Arguments required: ...')
}

args.fout = args[1]
args.title = args[2] == 'True'
args.info = args[3] == 'True'
args.temp = args[4] == 'True'
args.sig = args[5] == 'True'
args.fmt = args[6]

args.width = 10
args.height = 5

if (args.fmt == 'pdf') {
    cair_pdf(args.fout, width=args.width, height=args.height, onefile=TRUE)
} else if (args.fmt == 'png') {
    fimg = png
    args.width = 800
    args.height = 400
    png(args.fout, width=args.width, height=args.height)
} else if (args.fmt == 'svg') {
    svg(args.fout, width=args.width, height=args.height)
}

if (!args.title)
    par(mar=c(5, 4, 1, 2) + 0.1)

for (i in 1:nrow(kz.dives)) {
    dive = kz.dives[i,]
    dp = kz.profiles[kz.profiles$dive == i, ]
    dive_time = dp$time / 60.0
    xlim = range(dive_time)
    ylim = rev(range(dp$depth))
    plot(NA, xlim=xlim, ylim=ylim,
        xlab='Time [min]', ylab='Depth [m]')

    # deco info
    if (any(!is.na(dp$deco_time))) {
        deco_depth = approxfun(dp$time, dp$deco_depth,
            method='constant', f=1)(dp$time)

        n = length(dp$time)
        dc = rep(rgb(0.90, 0.90, 1.0), n - 1)
        dc[which(dp$deco_alarm)] = rgb(1.0, 0.50, 0.50)
        rect(dive_time[1:n - 1], deco_depth[1:n - 1], dive_time[2:n], rep(0, n - 1),
            col=dc, border=dc)
    }

    # then the grid
    minor.tick(nx=5, ny=2)
    grid()

    # and finally the dive profile
    lines(dive_time, dp$depth, col='blue')
    if (args.title)
        title(sprintf('Dive %s', dive$datetime))

    if (args.info) {
        d_min = round(dive$duration / 60)
        d_sec = round(dive$duration %% 60)
        info = sprintf('t = %d:%d\n\u21a7 = %.1fm\nT = %.1f\u00b0C',
            d_min, d_sec, dive$depth, dive$temp - 273.15)
        grid.text(info, x=0.85, y=0.25, just=c('left', 'bottom'),
            gp=gpar(cex=0.8, fontfamily='monospace'))
    }

    if (args.sig)
        grid.text(sprintf('generated by kenozooid ver. %s', kz.version),
            x=0.99, y=0.01, just=c('right', 'bottom'),
            gp=gpar(cex=0.6, fontface='italic'))
}


dev.off()

# vim: sw=4:et:ai
